id: I13C497A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:54:52+00:00'
last_modified: '2022-06-07T16:30:21.444889+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30387
  title: སྨན་དཔྱད་ཟླ་བའི་རྒྱལ་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AF26:
      image_group_id: I1PD442
      title: ''
      total_pages: 486
      order: 1
      base_file: AF26.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
