id: P002950
initial_creation_type: ocr
source_metadata:
  id: bdr:W30387
  title: སྨན་དཔྱད་ཟླ་བའི་རྒྱལ་པོ
  author: ''
  volumes:
    c0c99b50e6524675af8f7c0f8716c6b3:
      image_group_id: I1PD442
      title: ''
      volume_number: 1
      total_pages: 486
      base_file: v001.txt
